// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarefa_MVC_Core_CHAPELARIA.Data;

namespace Tarefa_MVC_Core_CHAPELARIA.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221025200448_createMigration")]
    partial class createMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Tarefa_MVC_Core_CHAPELARIA.Models.Vendas", b =>
                {
                    b.Property<int>("Id_vendas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_vendas");

                    b.Property<DateTime>("Data_compra")
                        .HasColumnType("Date");

                    b.Property<string>("Nome_chapeu")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome_formapag")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nomecliente")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Qtd")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id_vendas");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
