// <auto-generated />
using System;
using EscolaAmarelinha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolaAmarelinha.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221004232603_CreateTableAlunos")]
    partial class CreateTableAlunos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("EscolaAmarelinha.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAluno");

                    b.Property<string>("CursoAluno")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataMatriculaAluno")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneroAluno")
                        .HasColumnType("longtext");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<double>("MensalidadeAluno")
                        .HasColumnType("double");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
