// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarefa_MVC_Core_Agência_de_Empregos.Data;

namespace Tarefa_MVC_Core_Agência_de_Empregos.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221016042652_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Tarefa_MVC_Core_Agência_de_Empregos.Models.Curriculo", b =>
                {
                    b.Property<int>("Id_cur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_cur");

                    b.Property<string>("Cpf_candidato")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Escolaridade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Espanhol_nivel")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado_civil")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Frances_nivel")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ingles_nivel")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome_candidato")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<float>("Pretensao_sal")
                        .HasColumnType("float");

                    b.Property<string>("Rg_candidato")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_cur");

                    b.ToTable("Curriculos");
                });
#pragma warning restore 612, 618
        }
    }
}
